[tool.poetry]
name = "house-tool"
version = "0.1.0"
description = ""
authors = ["h-cave <124801533+h-cave@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
